apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  project: default
  source:
    path: examples/guestbook
    repoURL: https://github.com/JohnnyBeProgramming/poc-argocd.git
    targetRevision: HEAD
  destination:
      server: "https://kubernetes.default.svc"
      namespace: default