apiVersion: v1
kind: Secret
metadata:
  name: example-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/JohnnyBeProgramming/poc-argocd